apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meu-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: Web
  template: 
    metadata:
      labels: 
        app: Web
    spec:
      containers: 
      - name: site
        image: fabricioveronez/web-page:blue
        ports: 
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: service-web
spec: 
  selector: 
    app: Web #Configuração para todos os serviçços com a label "Web"
  ports: 
  - protocol: TCP
    port: 80
    nodePort: 30000 # -> Especificação para o Docker container fazer o vínculo do bind de porta.
  type: NodePort #Exposição em uma porta, entre 30000 e 32777